"""Build uncropped, WebP card previews without changing full-size project art.
Run from the repository root: python3 tools/generate-thumbnails.py
Requires Pillow and Node.js (the site itself has no build dependency).
"""
import json
import subprocess
from pathlib import Path
from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[1]
source = """
const fs=require('fs'),vm=require('vm');const ctx={window:{}};vm.createContext(ctx);
for(const name of ['projects-data.js','melahah-project.js'])vm.runInContext(fs.readFileSync('assets/js/'+name,'utf8'),ctx);
process.stdout.write(JSON.stringify(ctx.window.Projects));
"""
projects = json.loads(subprocess.check_output(['node', '-e', source], cwd=ROOT, text=True))
output = ROOT / 'assets/images/thumbnails'
output.mkdir(parents=True, exist_ok=True)
manifest = {}
original_bytes = 0
preview_bytes = 0
for project in projects:
    original = ROOT / project['cover']
    original_bytes += original.stat().st_size
    image = ImageOps.exif_transpose(Image.open(original))
    image.thumbnail((1024, 768), Image.Resampling.LANCZOS)
    destination = output / (project['slug'] + '.webp')
    image.save(destination, 'WEBP', quality=82, method=6)
    preview_bytes += destination.stat().st_size
    manifest[project['slug']] = {'src': str(destination.relative_to(ROOT)), 'width': image.width, 'height': image.height}
    if project.get('scrollPreview'):
        scroll = Image.open(ROOT / project['scrollPreview'])
        scroll.thumbnail((960, 20000), Image.Resampling.LANCZOS)
        path = output / (project['slug'] + '-scroll.webp')
        scroll.save(path, 'WEBP', quality=82, method=6)
        manifest[project['slug']]['scroll'] = str(path.relative_to(ROOT))
js = '''/** Generated by tools/generate-thumbnails.py. Full project art stays unchanged. */
(function () {
  var thumbnails = %s;
  (window.Projects || []).forEach(function (project) {
    if (thumbnails[project.slug]) project.thumbnail = thumbnails[project.slug];
  });
})();
''' % json.dumps(manifest, indent=2)
(ROOT / 'assets/js/project-thumbnails.js').write_text(js)
print(f'{len(projects)} uncropped thumbnails: {original_bytes:,} → {preview_bytes:,} bytes ({(1-preview_bytes/original_bytes)*100:.0f}% smaller)')
